word_list = [
    'anger',
    'angry',
    'fish',
    'catfish',
    'mouse',
    'mice',
    'farming',
    'paper',
    'acacia',
    'bark',
    'cube',
    'glue',
    'tape',
    'scissors',
    'water',
    'pollution',
    'carpooling',
    'honda civic',
    'legend of zelda',
    'disease',
    'corona',
    'memes',
    'phone',
    'samsung',
    'nose',
    'noise',
    'gandhi',
    'samuel jackson',
    'snopp dogg',
    'bonus',
    'textbook',
    'notebook',
    'laptop',
    'smartphone',
    'phone',
    'lion',
    'cow',
    'dear',
    'bear',
    'bird',
    'eagle',
    'mountain',
    'alps',
    'himalayas',
    'mother',
    'father',
    'uncle',
    'autocomplete',
    'kite',
    'unus annus',
    'pewdiepie',
    'jacksepticeye',
    'markiplier']